# cloudbuild.yaml

steps:
- name: gcr.io/cloud-builders/docker
  id: 'cloudbuild-android'
  env:
    - 'BUILD=$BUILD_ID'
    - 'PROJECT=$PROJECT_ID'
    - 'REV=$REVISION_ID'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/firebase-cloudbuild-demo/firebase-cloudbuild-demo/cloudbuild-android:${SHORT_SHA}',
    '-t', 'us-central1-docker.pkg.dev/firebase-cloudbuild-demo/firebase-cloudbuild-demo/cloudbuild-android:latest',

    # These are used by Cloud Build variable substitutions (as shown in screenshot_01.png):
    # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
    #'--build-arg', 'ANDROID_SDK_PACKAGES="${_ANDROID_SDK_PACKAGES"}',
    #'--build-arg', 'GRADLE_WRAPPER_VERSION=${_GRADLE_WRAPPER_VERSION}',

    # By default, static values are being used (build-trigger configuration not required)
    # When commenting these out, one has to run `./gradlew build` to fetch components
    # '--build-arg', 'ANDROID_SDK_PACKAGES=platform-tools platforms;android-33 build-tools;33.0.2 ndk;23.1.7779620',
    '--build-arg', 'ANDROID_SDK_PACKAGES=platform-tools platforms;android-33 build-tools;33.0.2',
    '--build-arg', 'GRADLE_WRAPPER_VERSION=7.4.2',

    # enable cloudbuild network
    '--network', 'cloudbuild',
    '.'
  ]
# - name: us-central1-docker.pkg.dev/firebase-cloudbuild-demo/firebase-cloudbuild-demo/cloudbuild-android
#   id: 'docker-pull'
#   args: ['cp', '-a', '.', '/persistent_volume']
#   volumes:
#   - name: data
#     path: /persistent_volume

# - name: gcr.io/cloud-builders/docker
#   id: 'gradle-build'
#   volumes:
#   - name: data
#     path: /persistent_volume
#   args: ['run', '-v', 'data:/workspace', '--rm', 'us-central1-docker.pkg.dev/firebase-cloudbuild-demo/firebase-cloudbuild-demo/cloudbuild-android', '/bin/sh', '-c', 'cd /workspace && ./gradlew mobile:assembleDebug && mv mobile/build/outputs/apk/debug/mobile-debug.apk mobile/build/outputs/apk/debug/$REPO_NAME-$SHORT_SHA-debug.apk && ls -la mobile/build/outputs/apk/debug/$REPO_NAME-$SHORT_SHA-debug.apk']



images:
- 'us-central1-docker.pkg.dev/firebase-cloudbuild-demo/firebase-cloudbuild-demo/cloudbuild-android:${SHORT_SHA}'
- 'us-central1-docker.pkg.dev/firebase-cloudbuild-demo/firebase-cloudbuild-demo/cloudbuild-android:latest'

options:
  logging: CLOUD_LOGGING_ONLY

# artifacts:
#   objects:
#     location: 'gs://${PROJECT_ID}-build-target/'
#     paths: ['/persistent_volume/app/build/outputs/apk/debug/']


