# cloudbuild.yaml

steps:
- name: gcr.io/cloud-builders/docker
  id: 'cloudbuild-android'
  env:
    - 'BUILD=$BUILD_ID'
    - 'PROJECT=$PROJECT_ID'
    - 'REV=$REVISION_ID'
  args: [
    'build',
    '-t', 'docker.pkg.dev/firebase-cloudbuild-demo/firebase-cloudbuild-demo/cloudbuild-android/cloudbuild-android:${SHORT_SHA}',
    '-t', 'docker.pkg.dev/firebase-cloudbuild-demo/firebase-cloudbuild-demo/cloudbuild-android/cloudbuild-android:latest',

    # These are used by Cloud Build variable substitutions (as shown in screenshot_01.png):
    # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
    #'--build-arg', 'ANDROID_SDK_PACKAGES="${_ANDROID_SDK_PACKAGES"}',
    #'--build-arg', 'GRADLE_WRAPPER_VERSION=${_GRADLE_WRAPPER_VERSION}',

    # By default, static values are being used (build-trigger configuration not required)
    # When commenting these out, one has to run `./gradlew build` to fetch components
    # '--build-arg', 'ANDROID_SDK_PACKAGES=platform-tools platforms;android-33 build-tools;33.0.2 ndk;23.1.7779620',
    '--build-arg', 'ANDROID_SDK_PACKAGES=platform-tools platforms;android-33 build-tools;33.0.2',
    '--build-arg', 'GRADLE_WRAPPER_VERSION=7.4.2',

    # enable cloudbuild network
    '--network', 'cloudbuild',
    '.'
  ]

-
options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'docker.pkg.dev/firebase-cloudbuild-demo/firebase-cloudbuild-demo/cloudbuild-android/cloudbuild-android:${SHORT_SHA}'
- 'docker.pkg.dev/firebase-cloudbuild-demo/firebase-cloudbuild-demo/cloudbuild-android/cloudbuild-android:latest'

# artifacts:
#   objects:
#     location: 'gs://${PROJECT_ID}-build-target/'
#     paths: ['/persistent_volume/app/build/outputs/apk/debug/']


